### ISSUE TITLE
CORS for DOL APIs

### ISSUE THREAD

**Issue by tyronegrandison** [USDepartmentofLabor/DOLAPI#10]
The CENSUS CitySDK team (https://github.com/uscensusbureau/citysdk) would like to include DOL APIs.  

CORS header support is a requirement for CitySDK. 

DOL and BLS APIs do not support it. 

We want to use api.data.gov as a means of adding CORS to DOL and BLS APIs

**Comment by MikePulsiferDOL** [comment]
Our efforts are being put into v2 of our API, due to be released June 26. (we're in the release phase now)  This is something we can look into for a summer release.

**Comment by MikePulsiferDOL** [comment]
Please see https://github.com/USDepartmentofLabor/Quarry/issues/9.
