### ISSUE TITLE
Filter Child Tables by activity_nr??

### ISSUE THREAD

**Issue by cosmoKenney** [USDepartmentofLabor/DOLAPI#19]
Using the filter column api documented here: https://developer.dol.gov/accessing-the-apis-using-http-requests/#apiv2

I can filter the Inspection table on activity_nr:
`https://data.dol.gov/get/inspection/format/json/limit/100/filter_column/ACTIVITY_NR=104757273`

However when trying to get the Related Activity by the parent activity_nr like this:
`https://data.dol.gov/get/related_activity/format/json/limit/10/filter_column/ACTIVITY_NR=104757273`
I get an error:
```json
{
    "status": "0",
    "error": "Not Acceptable. Check suggested format."
}
```

The table documentation here: 
https://developer.dol.gov/health-and-safety/dol-osha-enforcement/#osha_related_activity
describes activity_nr as "Identifies the parent inspection" so the activity_nr field should be available to filter on. Makes no sense, otherwise, since it is a child of the Inspection. 

Note that filtering by other columns in Related Activity works: 
`https://data.dol.gov/get/related_activity/format/json/limit/10/filter_column/rel_act_nr=70352018`
but that's not useful.

How can I get this to work?

**Comment by cosmoKenney** [comment]
@MikePulsiferDOL @AlexMeasureDOL @konklone Is the DOL API maintained anymore?

**Comment by cosmoKenney** [comment]
Anyone?

**Comment by giridhar** [comment]
@cosmoKenney , I have checked the columns and looks like activity_nr  column doesn't exist in related_activity. we will reach out to the data owner and get back to you.

**Comment by giridhar** [comment]
@cosmoKenney  please check now.

**Comment by giridhar** [comment]
![Screen Shot 2020-04-29 at 11 03 28 AM](https://user-images.githubusercontent.com/57400/80611893-3a8ed780-8a09-11ea-8fb3-47f1926f9472.png)

**Comment by cosmoKenney** [comment]
@giridhar thanks so much for looking into this. Related activity is working fine now. 
I've also tested all the other endpoints successfully except Accident. For some reason I cannot pull Accident by SUMMARY_NR:
`https://data.dol.gov/get/accident/offset/1/limit/5/filter_column/summary_nr=200263747`
And inspection/activity number does not work either.

**Comment by giridhar** [comment]
That's odd, It seems to work for me. 


![Screen Shot 2020-05-18 at 9 35 56 AM](https://user-images.githubusercontent.com/57400/82219410-41fc1f00-98eb-11ea-913c-db7a2f02d876.png)

**Comment by cosmoKenney** [comment]
@giridhar again thanks for the response. 
I just get an empty array back:
![image](https://user-images.githubusercontent.com/3654426/82579505-c1cff680-9b42-11ea-81fe-60dd6df493a3.png)

**Comment by cosmoKenney** [comment]
@giridhar my uri had offset specified. If I leave that out I get a result.

I think we can close this issue all of the endpoints are g2g for me now.

Thanks!
