### ISSUE TITLE
Data sets around pay for men, woman and race

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/DOLAPI#8]
From the DOL blog comments:

We are looking for data sets around pay for men, woman and race. I searched the site and found average pay by occupation, but did not see data set breakdown by other demographics. Is this type of information available?

**Comment by jfc3-dol** [comment]
I know Women's Bureau has that kind of information on the website, but do not know if they have it any datasets.

Here are examples about gender, race, age, etc. on this page:

http://www.dol.gov/wb/stats/latest_annual_data.htm

**Comment by MikePulsiferDOL** [comment]
http://developer.dol.gov/expanding-growth/bls-current-population-survey-cps/#LE_SEXS provides some of the data.  Will reach out to see if we can get the rest published.
